# Generated by Django 6.0.6 on 2026-06-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_original', models.CharField(max_length=2000)),
                ('codigo_curto', models.CharField(max_length=6)),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
