# Generated by Django 6.0.6 on 2026-06-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='codigo_curto',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_original',
            field=models.URLField(max_length=2000),
        ),
    ]
